### ISSUE TITLE
iPhone6 s plus support?

### ISSUE THREAD

**Issue by seishonagon** [exyte/ARTetris#5]
Hi, 
supposedly iPhone 6s+ is supported by ARKit, but I just get a video feed from my camera, with nothing happening on the screen. 
I've tried a few other tutorials and it seems the ones that use spriteKit don't work on 6sPlus. Is this a known limitation? Am I doing something wrong?
Paul.

**Comment by ystrot** [comment]
Hi Paul,

iPhone 6s+ is supported by ARKit, otherwise application will crash. If you see a camera view then everything is fine. Now you need to point your camera to some plane (floor, table top, etc.). You may need to move your device a little bit to force ARKit to find the plane bounds. Once it will be found, you will see Tetris well on this plane.

**Comment by rdvt** [comment]
Do you have ios 11 beta in your iphone 6s?
